import Head from "next/head";
import BootstrapCarousel from "../carousels/Bootstrap";

const Slider = () => {

    return (
        <div>
          <Head>
            <title>Next.js Carousels</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
            <BootstrapCarousel />
          </main>
        </div>
      );
}

export default Slider;